# Generated by Django 2.1.5 on 2019-02-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionInYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4)),
                ('amount', models.CharField(max_length=25)),
            ],
        ),
    ]
