# Generated by Django 2.1.5 on 2019-02-01 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emissioninyear',
            old_name='amount',
            new_name='emission_amount',
        ),
        migrations.AlterUniqueTogether(
            name='emissioninyear',
            unique_together={('country_name', 'year')},
        ),
    ]
