# Generated by Django 2.1.5 on 2019-02-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190201_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissioninyear',
            name='emission_amount',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
